spring.datasource:
  primary:
    jdbc-url: jdbc:postgresql://localhost:5432/example
    username: ...
    password: ...
  sits:
    jdbc-url: jdbc:oracle:thin:@//example.warwick.ac.uk:1521/example.warwick.ac.uk
    username: ...
    password: ...

logging.level:
  org.hibernate.SQL: DEBUG

spring.profiles.active:
  - dev
  - app
  - api
  - scheduling
