version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:6.8.4
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es

  kibana:
    image: kibana:6.8.4
    ports:
      - "5601:5601"
    networks:
      - es
    depends_on:
      - elasticsearch

networks:
  es:

