spring.resources.chain.strategy.content:
  enabled: true
  paths: /assets/**

server:
  forward-headers-strategy: native
  port: 8080

camcat.roles:
  admin-webgroup: in-camcat-admin
  sysadmin-webgroup: in-camcat-sysadmin
  masqueraders-webgroup: in-camcat-masqueraders

audit.application-key: camcat

spring.datasource.sits:
  schema: INTUIT
  data-source-properties:
    oracle.jdbc.fanEnabled: FALSE

spring.quartz:
  scheduler-name: camcat
  job-store-type: jdbc
  auto-startup: false
  overwrite-existing-jobs: true
  properties:
    org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

memcached.cache:
  # By default, cache everything for 1 day. This is a *hard* TTL, if you need soft TTLs, consider using VariableTtlCacheHelper
  expirations: 86400
  operation-timeout: 250

---

spring.profiles: scheduling
spring.quartz.auto-startup: true

